### ISSUE TITLE
No gradient in scatter example

### ISSUE THREAD

**Issue by jeffbaumes** [Kitware/candela#154]
I notice that the gradient on the scatter legend does not show up. Also some antialiasing effects to help image testing makes the examples not as nice-looking. Can/should we build a nicer version of the examples without the special CSS?

**Comment by ronichoudhury** [comment]
Do you have an example of the antialiasing effects? In any case, yes we should make a more human-viewable set of examples; that should maybe be part of #135.

I'm looking into the gradient problem.

**Comment by ronichoudhury** [comment]
So this happens because of the SVG def URL for the gradient, which is created using a fragment identifier against the current URL. Technically, to have multiple fragments in a URL, you are supposed to use something like the multiple query arguments syntax, but I think we might be better served by fixing #135 to use individual pages instead of dispatching on the fragment ID. This is a case of two systems each doing the right thing, adding up to the wrong thing when they do it together.

**Comment by ronichoudhury** [comment]
This was fixed some time ago.
