### ISSUE TITLE
Store / filter items based on Resonant lab version numbers

### ISSUE THREAD

**Issue by alex-r-bigelow** [Kitware/candela#255]
We run into this problem a lot: a given dataset or project item won't work with whatever version of resonant lab is being used.

Two ideas:
- For broader deployment, we should store Resonant Lab version numbers as metadata in these items, so we can update old items' metadata if/when necessary. Users should never have to deal with file version issues (MS Office, anyone?)
- For internal development, we could instead store the current branch name as the version (or commit hash?) via some kind of `subprocess.check_output(["git", "status"])` voodoo, so that 1) we don't run into bugs that have nothing to do with the current version that we're working on, and 2) we don't accidentally corrupt dataset/project metadata that was supposed to be stable. In development mode, we'd hide any items in the interface that don't match the current branch

**Comment by jeffbaumes** [comment]
I feel the longer-term answer is that we settle on a format and then stop breaking compatibility. That is, we enumerate a list of what is allowed to change in point/patch releases, e.g.

* Add a visualization
* Add an optional option
* Add support for a new datatype to an option

And what cannot, e.g.

* Remove/rename a visualization
* Remove an option
* Add a required option
* Remove support for a datatype on an option

In theory this supports forwards compatibility also, since new visualizations and options would just be ignored but kept in place in the database.

If we ever do one of the things on the second list (which could happen on major version release of Candela), we would decide how to handle things in ResonantLab (backwards compatibility code paths, not supporting prior versions, etc.).

Until we get to 1.0, I'm not sure we should use development time for putting some heavy machinery in place like versioning. What we can do is make ResLab code more resilient to schema changes and standardize on schema as quickly as possible.

**Comment by ronichoudhury** [comment]
I agree with Jeff. The sledgehammer way to solve the problem in the meantime is to have a script that can repopulate a target collection with several data sets, visualizations, and projects that all work properly, and just use this to "reset" whenever things get messy, etc. This may just be the `populateGirder.py` script that already exists, with some tweaking to allow it to e.g. empty a collection before performing the upload or something like that.

**Comment by alex-r-bigelow** [comment]
It'd be really nice to be able to settle on a format/schema, but I think in practice it may not be so easy. The optional options are a great example: it took me a while today to realize that I was dealing with a project that had cached a Candela spec without the optional option that we just added... and I needed to create a new project to get something fresh with the new `optional` field in it to get things to render properly. Obviously, I shouldn't be caching Candela specs in metadata (live introspection would have avoided this particular issue), but I think in general we're likely going to be adding stuff like this all the time to project and/or dataset metadata. The changes themselves will necessitate changes to these lists.

ResLab already probes metadata to see if an item can be opened (is this a project or a dataset or neither?)... this change would simply be one additional field, plus storing the version metadata (and probably a config switch somewhere to only show development mode items). The sledgehammer would probably be an equivalent amount of work, but would add a lot more time to an already lengthy build process.

In either approach, a public-facing deployment would need to handle updating old files (backward compatibility) / ignoring new stuff in newer files (forward compatibility)—I agree that's an icebox feature.

**Comment by jeffbaumes** [comment]
@alex-r-bigelow Let's suppose we do add a version to every project, which would be a Git hash in the general development case. What would we do with that? Just check against the current app/Candela version and refuse to load if it doesn't match? That would invalidate everything on every code change, meaning wiping out everything like @ronichoudhury suggests would perform the same task. I suppose we could still leave things but put up a warning flag if a project creation version differs from the app version, but again in development that warning would just be there nearly all the time.

If we tried to do something smarter, how would we compare versions, and what would we do in each case? The commit hash of the app might be ahead of, behind, or both ahead and behind in different ways if it is a branch, compared to the hash of the project that we are attempting to load. It's not clear what things would be considered "close enough" to attempt to load.

The pain you went through with the `optional` parameter had a good result: it exposed a bug that we can change to make the app more resilient to schema changes.

**Comment by alex-r-bigelow** [comment]
We'd probably use the branch name, not the git hash, and _ignore_ (not delete) things that don't match when we're in development mode—it would give us a nice sandbox environment without having to trash our girder installation every time we branch off and try something. And when the branch is finished and merged, any test items that we made in the process would get ignored the other way.

Deployed versions would get special behavior—if the branch is master, release, or there is no branch info (e.g. someone's downloaded the zip instead of using `git clone`), then items would get real version numbers instead of branch names, and all items with real version numbers would be visible (even if the version number doesn't match—this is where the back/forward icebox feature comes in)

**Comment by ronichoudhury** [comment]
I think versioning files once we reach 1.0 is probably a good idea, along
the lines you are suggesting Alex. In the meantime, can we do something
simpler like create specialized folders with the name of the branch or
otherwise identified by what experimentation is going on? That way, when
you switch branches, you'll just switch to a different folderful of
projects etc. It would basically be a crude, non-automated version of what
you're describing now. If this does solve the problem, then it avoids
adding what seems like relatively heavy post-1.0 machinery to the project
now when other more critical things remain to be solidified. What do you
think?

**Comment by alex-r-bigelow** [comment]
Hmm... extra folders seem like the more refined way, i.e. more work. My dumb ignore-if-it-doesn't-match-the-current-branch approach is probably the crude easy one :smile:. I was thinking for now, we'd *just* use the branch name, so that anything you make on master will stay on master, and probably add the *real* versioning logic in its place later, like you say, when we reach 1.0.

It does leave housekeeping a little messy. Right now we have to go through and trash temporary branch items manually, and my approach wouldn't change that—your folder idea would definitely fix that problem, but cleaning out old test items seems like a minor concern at the moment.

**Comment by jeffbaumes** [comment]
I think I understand the utility a bit more @alex-r-bigelow, thanks for explaining. And I agree an extra metadata field seems similar in complexity to folders, so I think whatever is most convenient could be used.

We're really just talking about developer sanity here, so if a small bit of metadata could be added to help the development process I think we could do that. If we are losing tens of hours to something that could be remedied in 2 hours of work, we should do it. @alex-r-bigelow I think you can decide when we've reached a tipping point on this since it's affecting you most.
