### ISSUE TITLE
Remove start with visualization until it's functional

### ISSUE THREAD

**Issue by jeffbaumes** [Kitware/candela#26]
Currently I cannot select a visualization so that should be removed for now.

**Comment by alex-r-bigelow** [comment]
Turns out there was a bug! Thanks for the heads up. I've hard-coded Scatter as the only visualization in the library for now in e6af54cd6494cd591b0599867eb64b08951e9954.

Rather than hard-code too many routes through the UI that we'll discard later, I think the ideal way forward would be to add a default dataset to the Scatter visualization that gets added if they haven't already picked a dataset. I'm wondering if there is a best place to specify this... putting it in the VisualizationComponent API would imply knowledge about what datasets are available in some Girder instance somewhere.

We could do it the other way where the interface just picks one of the available datasets that happens to specify the Scatter visualization as its default... but this feels backward to me. @ronichoudhury , any thoughts about the best way to specify default datasets for a visualization?

**Comment by jeffbaumes** [comment]
I think current functionality (a blank vis until data is selected) is fine for the near term. I'd rather not include complex defaulting logic now that we might throw away later. I'm worried about the app doing something "smart" that sometimes leaves the user wondering. Probably a large overlay indicator in the vis panel like "No data is selected, please open the data panel and choose data for this visualization". I saw this post a while ago - good "empty states" might be better than trying to populate the view with something smart.

http://tympanus.net/codrops/2013/01/09/designing-for-the-empty-states/

**Comment by ronichoudhury** [comment]
+1 to Jeff's idea of an overlay. That's precisely the image I had in mind before I started reading Jeff's comment :-D

**Comment by jeffbaumes** [comment]
I'm going to open another issue relating to an "empty view" and close this one.
