### ISSUE TITLE
Opening public project fails

### ISSUE THREAD

**Issue by aronhelser** [Kitware/candela#431]
I was trying out resonant labs, and I'm not logged in or registered. 

I tried opening one of the 'Public Projects', and I got the "I've made a huge mistake" dialog:
Project copied to an unknown location. 
 Stack Trace: Error: Project copied to an unknown location. at eval (webpack:///./models/UserPreferences.js?:93:45)

**Comment by ronichoudhury** [comment]
Thanks for the report @aronhelser! Will look into this.

**Comment by ronichoudhury** [comment]
This problem seems to be fixed now, though I didn't do anything to fix it. It may have been a recent update to the Resonant Lab instance (on October 10), or else it may have been due to updating Girder at the same stroke.

@aronhelser I'm going to close this issue but if the problem appears again please don't hesitate to re-open and drop us another note here.
